spring:
  mail:
    host: smtp.gmail.com
    username: vasudevpanchani80@gmail.com
    password: rckrtaxkgymlivpe
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true       


